### PR TITLE
fix: apply generic type in static forRoot method of svg-icons.module.ts

### PR DESCRIPTION
**Pull request by patrickmichalina**
## PR Checklist

Please check if your PR fulfills the following requirements:

- [x] The commit message follows our guidelines: CONTRIBUTING.md#commit
- [x] Tests for the changes have been added (for bug fixes / features)
- [x] Docs have been added / updated (for bug fixes / features)

## PR Type

What kind of change does this PR introduce?

```
[x] Bugfix
[ ] Feature
[ ] Code style update (formatting, local variables)
[x] Refactoring (no functional changes, no api changes)
[ ] Build related changes
[ ] CI related changes
[ ] Documentation content changes
[ ] Other... Please describe:
```

## What is the current behavior?

Issue Number: 13

## Does this PR introduce a breaking change?

```
[ ] Yes
[x] No
```

### CODE REVIEW

**Comment by patrickmichalina** [comment]
Issue: #13

**Comment by NetanelBasal** [comment]
Please follow the commit message guidelines.

**Comment by patrickmichalina** [comment]
Is this not ok?

**Comment by NetanelBasal** [comment]
https://github.com/ngneat/svg-icon/blob/master/CONTRIBUTING.md#-commit-message-guidelines

**Comment by patrickmichalina** [comment]
What a douche bag

**Pull request closed without merging**
